services:
  spotify-remote:
    image: ghcr.io/rdevhq/spotify-remote-ios9:main
    container_name: spotify-remote
    restart: unless-stopped
    ports:
      - "3010:3010"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - HA_WEBHOOK_URL=${HA_WEBHOOK_URL}
    volumes:
      - /DATA/AppData/spotify-remote/data:/data
    x-casaos:
      icon: https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Ftous-logos.com%2Fwp-content%2Fuploads%2F2018%2F05%2FLogo-Spotify.png&f=1&nofb=1&ipt=df4185186c88fcdb486447124b14c01410bd1a9cb2be108db90ee461ece6ca7d
